[tool.poetry]
name = "tapir"
version = "0.0.0"
description = "DNS TAPIR Python Library"
authors = ["Jakob Schlyter <jakob@kirei.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
http-message-signatures = "^0.5.0"
jsonformatter = "^0.3.2"
opentelemetry-instrumentation-fastapi = "^0.48b0"
opentelemetry-exporter-otlp = "^1.27.0"
opentelemetry-instrumentation-botocore = "^0.48b0"
opentelemetry-instrumentation-pymongo = "^0.48b0"
httpx = "^0.27.2"
redis = "^5.1.1"
expiringdict = "^1.2.2"
fastapi = "^0.115.2"
botocore = "^1.35.44"
pymongo = "^4.10.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
ruff = "^0.6.3"
pytest-ruff = "^0.4.1"
fakeredis = "^2.25.1"
pytest-httpx = "^0.32.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501", "I001"]

[tool.ruff.lint.isort]
force-sort-within-sections = false
combine-as-imports = true
split-on-trailing-comma = false
